### ISSUE TITLE
Problem z zespołami

### ISSUE THREAD

**Issue by Madziorex** [FazKarcz/lyricalAPP#2]
Nie da się dodać zespołu, trzeba i tak podać imię i nazwisko. Można dodać tabelkę 'band' i do niej dodawać pojedynczych autorów z 'authors', albo rozdzielić to na dwa i w band nie trzeba by było podawać imienia i nazwiska.

**Comment by FazKarcz** [comment]
![sad](https://github.com/FazKarcz/lyricalAPP/assets/92019651/ff8610b1-3b4a-453e-b6c1-a9cb633c83e4)

**Comment by FazKarcz** [comment]
Tabela Band z członkami, data założenia i coś jeszcze do niej?

**Comment by FazKarcz** [comment]
Albo zmienić tabele artist, tak że nie podajemy imienia i nazwiska tylko sam nickname, i wtedy by się tylko nazwę zespołu dawało, a jeśli ktoś (Dawid Podsiadło) nie ma nicku to wtedy w te pole jego imię i nazwisko es
